# 全局配置
global:
  scrape_interval: 15s # 搜罗targets数据间隔时间，默认1m
  evaluation_interval: 15s # 评估告警规则间隔时间，默认1m
  scrape_timeout: 10s # 搜罗targets数据超时时间，默认10s
  external_labels: # 额外的标签
    monitor: "network devices monitoring"

# 告警插件配置
alerting:
  alertmanagers: # 启动告警插件
    - static_configs: # 静态配置
        - targets: # 告警目标
          - alertmanager:9093 # 容器名称+端口

# 加载规则，并按照全局配置中的evaluation_interval定期评估规则
rule_files:
  - "/prometheus/rules/*.yml"

# 搜罗数据配置
scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "snmp-exporter"
    metrics_path: /snmp
    scheme: http
    static_configs:
      - targets: [ "snmp-exporter:9116" ]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: instance